<?php

use Illuminate\Database\Seeder;

//model
use App\Food;
use App\User;
use App\Category;
//zaninotto faker
use App\Services\Slug;

class CibiTableSeeder extends Seeder
{

    protected $foodList =
    [
        "Italiano" =>[
            //antipasti
            [
                "name"=> "Antipasto all'italiana",
                "course" => "Antipasto",
                "ingredients" => "Tagliere di salumi tipici e una selezione di formaggi locali. Servito con focaccia ed erbe miste.",
                "price" =>9 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Caprese",
                "course" => "Antipasto",
                "ingredients" => "Pomodori,mozzarella,origano, olio EVO",
                "price" =>6 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Tris di bruschette",
                "course" => "Antipasto",
                "ingredients" => "Tre bruschette di pane rustico tostato con paté di olive, pomodori, salsiccia e provola affumicata.",
                "price" =>7 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Carpaccio di manzo",
                "course" => "Antipasto",
                "ingredients" => "Carpaccio di manzo, rucola, scaglie di parmigiano, olio di oliva",
                "price" =>5 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            
            //primi
            [
                "name"=> "Farfalle al pomodoro",
                "course" => "Primo",
                "ingredients" => "Pomodori pelati bio, basilico , aglio , olio extravergine d'oliva",
                "price" =>7.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Spaghetti alla carbonara",
                "course" => "Primo",
                "ingredients" => "Uova, guanciale, pecorino romano, pepe nero",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Rigatoni all'amatriciana",
                "course" => "Primo",
                "ingredients" => "Pomodori pelati bio, guanciale, pecorino romano, peperoncino rosso, pepe nero",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Tortellini alla boscaiola",
                "course" => "Primo",
                "ingredients" => "Funghi, panna, prosciutto cotto, parmigiano, pepe nero",
                "price" =>7.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pasta alla norma",
                "course" => "Primo",
                "ingredients" => "Melanzana, pomodoro, ricotta di pecora, basilico",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Risotto alla milanese",
                "course" => "Primo",
                "ingredients" => "Contiene burro,midollo di vitello e brodo di carne e zafferano.",
                "price" =>7.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            //secondi
            [
                "name"=> "Cotoletta di vitello",
                "course" => "Secondo",
                "ingredients" => "Fettine di vitello panate (con uova e pangrattato) e fritte",
                "price" =>8 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Scaloppine al limone",
                "course" => "Secondo",
                "ingredients" => "Fettine di vitello, burro, farina 00, succo di limone, pepe",
                "price" =>8 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Grigliata mista",
                "course" => "Secondo",
                "ingredients" => "Salsiccie e lonza di maiale, braciole d'agnello",
                "price" =>12 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pesce spada alla Pantesca",
                "course" => "Secondo",
                "ingredients" => "Filetto di spada, capperi, olive, cipolla e pomodoro ciliegino",
                "price" =>12 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Parmigiana di melanzane",
                "course" => "Secondo",
                "ingredients" => "Melanzane, passata di pomodoro, fiordilatte, parmigiano, basilico",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Sformato di verdure",
                "course" => "Secondo",
                "ingredients" => "Melanzane, patate rosse, zucchine, scamorza affumiacata, peperoni, parmigiano",
                "price" =>11 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            //contorni
            [
                "name"=> "Olive all'ascolana",
                "course" => "Contorno",
                "ingredients" => "Olive,macinato misto di carne",
                "price" =>4.5 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Verdure grigliate",
                "course" => "Contorno",
                "ingredients" => "Melanzane e zucchine grigliate, olio EVO",
                "price" =>4 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Patate Fritte",
                "course" => "Contorno",
                "ingredients" => "Patate",
                "price" =>3 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Insalata mista",
                "course" => "Contorno",
                "ingredients" => "Insalata, rucola, cipolla, valeriana, spinacino",
                "price" =>3 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            //dolci
            [
                "name"=> "Tiramisù",
                "course" => "Dolce",
                "ingredients" => "Savoiardi, mascarpone, caffé, zucchero, uova",
                "price" =>3.5 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Panna cotta al cioccolato",
                "course" => "Dolce",
                "ingredients" => "Panna cotta con cioccolato al latte",
                "price" =>3 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Salame di cioccolato",
                "course" => "Dolce",
                "ingredients" => "Cioccolato fondente,biscotti secchi, rum",
                "price" =>3.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Cannoli siciliani",
                "course" => "Dolce",
                "ingredients" => "Ricotta di pecora, frutta candita, gocce di cioccolato",
                "price" =>4 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            //piatto unico
            [
                "name"=> "Insalatona di riso",
                "course" => "Piatto Unico",
                "ingredients" => "Riso, tonno, pomodoro, prosciutto cotto, piselli, sottaceto, olive",
                "price" =>6.80 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,            
            ]
        ],
        'Cinese'=>[
             //piatto unico
             [
                "name"=> "Alga wakame",
                "course" => "Contorno",
                "ingredients" => "Alga wakame, semi di sesamo, salsa",
                "price" =>3 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,            
             ],
             [
                "name"=> "Insalata di alghe Kombu",
                "course" => "Contorno",
                "ingredients" => "Alga Kombu, scalogno, cipollotto, zenzero",
                "price" =>3.60 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,            
             ],
             [
                "name"=> "Menù assaggio",
                "course" => "Piatto Unico",
                "ingredients" => "Una selezione di piatti tipici cinesi",
                "price" =>18 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,     
             ],
             //antipasti
             [
                "name"=> "Edamame",
                "course" => "Antipasto",
                "ingredients" => "Fagioli di soia lessati",
                "price" =>3.20 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Eby Gyoza",
                "course" => "Antipasto",
                "ingredients" => "Ravioli di gamberi al vapore",
                "price" =>3.90 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Ebi Tai",
                "course" => "Antipasto",
                "ingredients" => "Gamberi avvolti da pasta fillo,fritti",
                "price" =>4.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Sake Cytro",
                "course" => "Antipasto",
                "ingredients" => "Salmone, cetriolo, maionese, salsa",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Miso shiru",
                "course" => "Antipasto",
                "ingredients" => "Zuppa di miso con alghe e tofu",
                "price" =>3.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Involtini primavera",
                "course" => "Antipasto",
                "ingredients" => "Carote, cavolo cappuccio ,cipolle bianche, pepe bianco",
                "price" =>3.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            //primi
            [
                "name"=> "Riso cantonese",
                "course" => "Primo",
                "ingredients" => "Uova, prosciutto cotto, piselli, erba cipollina",
                "price" =>3.30 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Riso con gamberi",
                "course" => "Primo",
                "ingredients" => "Gamberi, piselli, uova",
                "price" =>3.80 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Spaghetti alla piastra con gamberi",
                "course" => "Primo",
                "ingredients" => "Gamberi, surimi, piselli, zucchine, uova",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Riso saltato con salmone e verdure",
                "course" => "Primo",
                "ingredients" => "Salmone, piselli, zucchine, carote, cipolla, uova",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Gnocchi di riso con verdure",
                "course" => "Primo",
                "ingredients" => "Piselli, zucchine, carote, cipolla, erba cipollina",
                "price" =>3.80 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            //secondi
            [
                "name"=> "Pollo con bambù e funghi",
                "course" => "Secondo",
                "ingredients" => "Straccetti di pollo, funghi, bambù",
                "price" =>4.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pollo alle mandorle",
                "course" => "Secondo",
                "ingredients" => "Straccetti di pollo, mandorle, carote, bambù",
                "price" =>4.30 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Maiale in salsa agrodolce",
                "course" => "Secondo",
                "ingredients" => "Maiale, cipollotti, salsa agrodolce",
                "price" =>4.30 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Tofu stufato",
                "course" => "Secondo",
                "ingredients" => "Tofu saltato con verdure",
                "price" =>4.30 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            //dolci
            [
                "name"=> "Gelato fritto",
                "course" => "Dolce",
                "ingredients" => "Gelato alla vaniglia fritto",
                "price" =>4.30 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Tiramisù",
                "course" => "Dolce",
                "ingredients" => "Savoiardi, mascarpone, caffé, zucchero, uova",
                "price" =>3.5 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Panna cotta al cioccolato",
                "course" => "Dolce",
                "ingredients" => "Panna cotta con cioccolato al latte",
                "price" =>3 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Sake",
                "course" => "Bevande",
                "ingredients" => "Bevanda alcolica ottenuta dal riso (0.25cl)",
                "price" =>2.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
        ],
        //libanese
        'Libanese' => [
            [
                "name"=> "Tabbouleh libanese",
                "course" => "Antipasto",
                "ingredients" => "Prezzemolo fresco, menta, bulgur, pomodori, cipolle, succo di limone, olio, sale",
                "price" =>5.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Sayadyeh ",
                "course" => "Primo",
                "ingredients" => "Riso, ,orata, brodo di pesce, paprika dolce, cumino, cannella, pimento, arancie, limone, prezzemolo, zenzero",
                "price" =>5.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Sayadyeh",
                "course" => "Piatto Unico",
                "ingredients" => "Riso, ,orata, brodo di pesce, paprika dolce, cumino, cannella, pimento, arancie, limone, prezzemolo, zenzero",
                "price" =>10.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Kobeba (Polpettine farcite libanesi)",
                "course" => "Secondo",
                "ingredients" => "Bulgur, carne di agnello, cipolle, farina, peperoncino, olio, cannella, pinoli, menta, brodo",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Baba Ghanoush",
                "course" => "Antipasto",
                "ingredients" => "Melanzane, aglio, tahin, olio, limone, sale",
                "price" =>5.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Batata Harra",
                "course" => "Contorno",
                "ingredients" => "Patate, aglio, coriandolo, peperoncino, olio, sale",
                "price" =>3.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 1,
            ],
            [
                "name"=> "Fattoush ",
                "course" => "Contorno",
                "ingredients" => "Pomodori, Cetrioli  Cipolla, Lattuga , Ravanelli , Prezzemolo ,Menta 
                Succo di limone  Sale, Olio extravergine",
                "price" =>4.20 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 1,
            ],
            [
                "name"=> "Imjadra",
                "course" => "Primo",
                "ingredients" => "Bulgur, noci, cipolla, menta, olio, sale, pepe",
                "price" =>4.20 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Musakhan",
                "course" => "Secondo",
                "ingredients" => "Pollo, cipolla, pane pita, sale, pepe, polvere di 5 spezie",
                "price" =>6.80 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Fagottini di spinaci libanesi",
                "course" => "Antipasto",
                "ingredients" => "Spinaci, limone, cipolle, prezzemolo, menta, farina, lievito di birra, olio, sale",
                "price" =>4.20 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Awamaat",
                "course" => "Dolce",
                "ingredients" => "Farina, lievito fìdi birra, acqua, acqua di fiori di arancio, zucchero",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Ganache al latte",
                "course" => "Dolce",
                "ingredients" => "Latte intero, cioccolto fondente",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
        ],
        //hamburger
        'Hamburger'=>[
            [
                "name"=> "Ribs",
                "course" => "Secondo",
                "ingredients" => "Costolette di manzo marinate",
                "price" =>12.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Insalatona verde",
                "course" => "Contorno",
                "ingredients" => "Insalata iceberg, cetrioli, mais ,cipolla",
                "price" =>5.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Mini-spiedini assortiti",
                "course" => "Antipasto",
                "ingredients" => "Spiedini di manzo e maiale assortiti",
                "price" =>5.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],            
            [
                "name"=> "Gelato",
                "course" => "Dolce",
                "ingredients" => "Gusti assortiti",
                "price" =>3.0 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pasta la pomodoro",
                "course" => "Primo",
                "ingredients" => "Passata di pomodoro,basilico",
                "price" =>4.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Veggie Burger",
                "course" => "Piatto Unico",
                "ingredients" => "Hamb.di barbabietola al piatto con carpaccio di verdure, pomodoro, salsa yogurt e chips",
                "price" =>7.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "CheeseBacon Burger",
                "course" => "Piatto Unico",
                "ingredients" => "Hamb. con bacon, cheddar, ketchup e patatine chips",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Acapulco",
                "course" => "Piatto Unico",
                "ingredients" => "Manzo, guacamole, bacon, cipolle alla piastra, salsa BBQ",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Nero di napoli",
                "course" => "Piatto Unico",
                "ingredients" => "Manzo, pane nero al carbone vegetale, mozzarella fritta, ketchup crudo, rucola, cipolle
                caramellate e salsa hot chipotle",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Spaccato",
                "course" => "Piatto Unico",
                "ingredients" => "Manzo con cheddar,crema di nduja di Spilinga, melanzane, pomodoro",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Las VEGANS",
                "course" => "Piatto Unico",
                "ingredients" => "Hamb. di seitan con crema di olive, pomodoro, melanzane, insalata, salsa allo yogurt",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Campagna",
                "course" => "Piatto Unico",
                "ingredients" => "Manzo,funghi misti, bacon, scamorza, crema di funghi tartufata, maionese",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Patatine chips",
                "course" => "Contorno",
                "ingredients" => "Chips di patate fritte",
                "price" =>3.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Onion Rings",
                "course" => "Contorno",
                "ingredients" => "Anelli di cipolla impanati e fritti",
                "price" =>3.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
        ],
        'Pizza'=> [
            [
                "name"=> "Svalvolata",
                "course" => "Piatto Unico",
                "ingredients" => "Pomodoro, fiordilatte, salsiccia secca piccante",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Amatriciana",
                "course" => "Piatto Unico",
                "ingredients" => "Pomodoro, guanciale, pecorino romano, pepe cuvèe",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Fresca",
                "course" => "Piatto Unico",
                "ingredients" => "Pomodoro, bufala, orgiano, basilico, alici",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],            
            [
                "name"=> "Fresca",
                "course" => "Piatto Unico",
                "ingredients" => "Pomodoro, bufala, orgiano, basilico, alici",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Vegetariana",
                "course" => "Piatto Unico",
                "ingredients" => "Fiordilatte, zucchine e melanzane grigliate, funghi, olive, baslico",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Il mare",
                "course" => "Piatto Unico",
                "ingredients" => "Pomodoro, alici, stracciatella, origano, capperi",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "La Campagnola",
                "course" => "Piatto Unico",
                "ingredients" => "Prosciutto crudo, stracciatella, pomodoro secco",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Mora",
                "course" => "Piatto Unico",
                "ingredients" => "Mortadella, ricotta, agretti, zeste di limone",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Delicata",
                "course" => "Piatto Unico",
                "ingredients" => "Fiordilatte, rucola, pomodrini, grana in scaglie",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Patatine chips",
                "course" => "Contorno",
                "ingredients" => "Chips di patate fritte",
                "price" =>3.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Anelli di cipolla",
                "course" => "Contorno",
                "ingredients" => "Anelli di cipolla impanati e fritti",
                "price" =>3.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Suppli",
                "course" => "Antipasto",
                "ingredients" => "Riso, mozzarella, passata di pomodoro, carne macinata",
                "price" =>5.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Crocchette di patate",
                "course" => "Antipasto",
                "ingredients" => "Crocchette di patate",
                "price" =>4.5 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Torta Paradiso",
                "course" => "Dolce",
                "ingredients" => "Uova, zucchero a velo, latte condensato",
                "price" =>3.5 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Sorbetto al limone",
                "course" => "Dolce",
                "ingredients" => "Sorbetto al limone, senza alcol.",
                "price" =>3.0 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Gelato",
                "course" => "Dolce",
                "ingredients" => "Gusti assortiti",
                "price" =>3.0 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Spaghetti allo scoglio",
                "course" => "Primo",
                "ingredients" => "Passata di pomodoro, frutti di mare, prezzemolo",
                "price" =>8.0 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Bistecca ai ferri",
                "course" => "Secondo",
                "ingredients" => "Bistecca ai ferri con rucola,sale limone",
                "price" =>10.0 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ]
        ],
        // Americano
        "Americano" =>[
            [
                "name"=> "Crostini di patate dolci con spada e stracchino",
                "course" => "Antipasto",
                "ingredients" => "pane, pesce spada, stracchino",
                "price" =>6.20 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Buffalo Wings",
                "course" => "Antipasto",
                "ingredients" => "pollo, salsa piccante, tabasco, salsa Worcester",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Coleslaw",
                "course" => "Antipasto",
                "ingredients" => "cavolo bianco, carota, cipolla",
                "price" =>4.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Corn chowder",
                "course" => "Antipasto",
                "ingredients" => "paprika, aglio, cipolla, patate, mais",
                "price" =>9.90 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Shrimp and grits",
                "course" => "Primo",
                "ingredients" => "gamberi, semolino",
                "price" =>6.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Mac&Cheese",
                "course" => "Primo",
                "ingredients" => "maccheroni, formaggio",
                "price" =>14.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Mission-style burrito",
                "course" => "Primo",
                "ingredients" => "riso, formaggio, salse, carne",
                "price" =>9.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Chicago-style deep-dish pizza",
                "course" => "Primo",
                "ingredients" => "Paprika affumicata, Paprika dolce, Pepe bianco, Pepe di cayenna, Anice in polvere",
                "price" =>12.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Crab cake",
                "course" => "Secondo",
                "ingredients" => "pane, uova, polpa di granchio",
                "price" =>16.30 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pulled Pork",
                "course" => "Secondo",
                "ingredients" => "Paprika affumicata, Paprika dolce, Pepe bianco, Pepe di cayenna, Anice in polvere",
                "price" =>12.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Gumbo",
                "course" => "Secondo",
                "ingredients" => "okra, carne, frutti di mare",
                "price" =>22.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Fried green tomatoes",
                "course" => "Secondo",
                "ingredients" => "pomodori verdi firtti",
                "price" =>12.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Patatine Fritte",
                "course" => "Contorno",
                "ingredients" => "patate",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Patate con Cheddar",
                "course" => "Contorno",
                "ingredients" => "patate, cheddar cheese",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Donut",
                "course" => "Dolce",
                "ingredients" => "vaniglia, coloranti alimentari, uova",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Apple Pie",
                "course" => "Dolce",
                "ingredients" => "mele, noce moscata, cannella in polvere, limone",
                "price" =>10.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Cinnamon Roll",
                "course" => "Dolce",
                "ingredients" => "zucchero, cannella",
                "price" =>6.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Cheesecake ai frutti di bosco",
                "course" => "Dolce",
                "ingredients" => "Formaggio, more, lamponi, mirtilli, ribes, succo di limone",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
        ],
 
        // Sushi
        "Sushi" =>[
            [
                "name"=> "Edamame",
                "course" => "Antipasto",
                "ingredients" => "fagioli di soia",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Moyashi",
                "course" => "Antipasto",
                "ingredients" => "Germogli di soia alla piastra",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Maguro Tataki",
                "course" => "Antipasto",
                "ingredients" => "Tonno scottato",
                "price" =>12.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Maguro Karupatcho",
                "course" => "Antipasto",
                "ingredients" => "Carpaccio di tonno con aceto di riso e cipollotti",
                "price" =>14.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Spicy Wakame",
                "course" => "Antipasto",
                "ingredients" => "Alghe giapponesi agro-piccanti",
                "price" =>4.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Gari",
                "course" => "Antipasto",
                "ingredients" => "Zenzero in salamoia",
                "price" =>5.90 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Riso Filetto",
                "course" => "Primo",
                "ingredients" => "Riso alla piastra con filetto mignon",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Riso Pollo",
                "course" => "Primo",
                "ingredients" => "Riso alla piastra con pollo in salsa tariyaki",
                "price" =>7.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Tendon",
                "course" => "Primo",
                "ingredients" => "Riso bianco con tempura",
                "price" =>10.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Spaghetti Udon",
                "course" => "Primo",
                "ingredients" => "Spaghetti di grano con misto mare",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Spaghetti Udon verdure",
                "course" => "Primo",
                "ingredients" => "Spaghetti di riso con verdure",
                "price" =>6.30 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Kani Rice",
                "course" => "Primo",
                "ingredients" => "Riso alla piastra con polpa di granchio",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Gamberi Tai",
                "course" => "Secondo",
                "ingredients" => "Gamberi fritti, pomodoro, insalata, avocado, salsa sesamo",
                "price" =>7.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Gamberi in agrodolce",
                "course" => "Secondo",
                "ingredients" => "Gamberi in agrodolce",
                "price" =>9.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Calamari Fritti",
                "course" => "Secondo",
                "ingredients" => "Calamari Fritti",
                "price" =>6.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Uramaki Philadelhia",
                "course" => "Piatto Unico",
                "ingredients" => "Pesce crudo, avocado, philadelphia",
                "price" =>15.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Sashimi",
                "course" => "Piatto Unico",
                "ingredients" => "Pesce crudo",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Nigiri",
                "course" => "Piatto Unico",
                "ingredients" => "Riso, pesce crudo",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Temaki",
                "course" => "Piatto Unico",
                "ingredients" => "Riso, pesce crudo, alghe",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Uramaki",
                "course" => "Piatto Unico",
                "ingredients" => "Riso, pesce crudo, avocado",
                "price" =>12.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Anmitsu",
                "course" => "Dolce",
                "ingredients" => "ananas, pesca, ciliegie",
                "price" =>5.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Castella",
                "course" => "Dolce",
                "ingredients" => "farina, uova, zucchero, sciroppo di amido",
                "price" =>4.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Warabimochi",
                "course" => "Dolce",
                "ingredients" => "matcha, sesamo e sciroppi",
                "price" =>6.30 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
        ],
 
        // Vegano
        "Vegano" =>[
            [
                "name"=> "Hummus",
                "course" => "Antipasto",
                "ingredients" => "Ceci precotti 600, Olio di sesamo, Paprika, Aglio, Pepe nero, Prezzemolo",
                "price" =>5.60 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Polpette di zucchine",
                "course" => "Antipasto",
                "ingredients" => "Zucchine",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Tartufini di Tofu e olive",
                "course" => "Antipasto",
                "ingredients" => " noci, rucola e frutti rossi",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Polpette di melanzane",
                "course" => "Antipasto",
                "ingredients" => "Melanzane",
                "price" =>5.30 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Felafel",
                "course" => "Antipasto",
                "ingredients" => "Ceci crudi, cumino, aglio, cipolle, prezzemolo",
                "price" =>10.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Lasagne Radicchio e Funghi",
                "course" => "Primi",
                "ingredients" => "Radicchio, funghi",
                "price" =>12.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pasta fredda",
                "course" => "Primo",
                "ingredients" => "Zucchine, pomodori freddi, Tofu",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Risotto vegan",
                "course" => "Primo",
                "ingredients" => "piselli e mantecatura di tahina",
                "price" =>11.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Tendon",
                "course" => "Primo",
                "ingredients" => "Riso bianco con tempura",
                "price" =>10.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Paccheri Ceci e Zucchine",
                "course" => "Primo",
                "ingredients" => "Crema di ceci, Zucchine",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Spaghetti di riso con verdure",
                "course" => "Primo",
                "ingredients" => "Spaghetti di riso con verdure",
                "price" =>11.30 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pasta e ceci",
                "course" => "Primo",
                "ingredients" => "Ceci bolliti",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Melanzane alla griglia",
                "course" => "Secondo",
                "ingredients" => "Melanzane alla griglia",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Zucchine alla griglia",
                "course" => "Secondo",
                "ingredients" => "Zucchine alla griglia",
                "price" =>5.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Tofu in agrodolce",
                "course" => "Secondo",
                "ingredients" => "Tofu in agrodolce",
                "price" =>6.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Seitan grigliato",
                "course" => "Secondo",
                "ingredients" => "Seitan grigliato",
                "price" =>5.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Vellutata di piselli",
                "course" => "Secondo",
                "ingredients" => "Crostino, Vellutata di piselli",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Polpette di tofu, pomodori secchi e olive",
                "course" => "Secondo",
                "ingredients" => "pomodori secchi, origano, maggiorana, olive, capperi e menta",
                "price" =>12.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Melanzane sott'olio",
                "course" => "Piatto Unico",
                "ingredients" => "Melanzane sott'olio",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Sandwich ripieno di crema di ceci e avocado con olive e rucola",
                "course" => "Piatto Unico",
                "ingredients" => "crema di ceci, avocado, olive e rucola",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Biancomangiare vegan alle mandorle",
                "course" => "Dolce",
                "ingredients" => "Mandorle, limone, amido di mais",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
        ],
 
        // Kebab
        "Kebab" =>[
            [
                "name"=> "Kebab",
                "course" => "Piatto Unico",
                "ingredients" => "Carni miste, pomodoro, insalata, salse",
                "price" =>5.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Kebab Menu",
                "course" => "Piatto Unico",
                "ingredients" => "Kebab, patatine fritte, bibita",
                "price" =>16.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Piadina Kebab",
                "course" => "Piatto Unico",
                "ingredients" => "Carni miste, pomodoro, insalata, salse, piadina",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Panino Kebab",
                "course" => "Piatto Unico",
                "ingredients" => "Carni miste, pomodoro, insalata, salse, panino",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Felafel",
                "course" => "Piatto Unico",
                "ingredients" => "Ceci crudi, Prezzemolo, cumino, aglio, cipolla",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Patatine Fritte",
                "course" => "Contorno",
                "ingredients" => "patate",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            
        ],
 
        // Messicano
        "Messicano" =>[
            [
                "name"=> "Antipasto crudo e avocado",
                "course" => "Antipasto",
                "ingredients" => "prosciutto crudo, avocado",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Nachos",
                "course" => "Antipasto",
                "ingredients" => "farina di mais, formaggio fuso",
                "price" =>6.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Uova alla messicana",
                "course" => "Antipasto",
                "ingredients" => "uova, peperoni rossi, peperoncino fresco, aglio, pepe nero, passata di pomodoro, prezzemolo, cipolle rosse",
                "price" =>4.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Guacamole",
                "course" => "Antipasto",
                "ingredients" => "avocado, cipolle, peperoncino rosso piccante, coriandolo, lime",
                "price" =>9.90 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Caldo de Vigilia",
                "course" => "Primo",
                "ingredients" => "baccalà già bagnato, spinaci, ceci, passato di pomodori, cipolla",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Paella alla messicana",
                "course" => "Primo",
                "ingredients" => "riso, pollo, polpa di maiale, gamberetti sgusciati, peperoncini, cipolla, aglio",
                "price" =>14.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Arroz a la mexicana",
                "course" => "Primo",
                "ingredients" => "riso, pomodori maturi, cipolla, aglio, coriandolo",
                "price" =>11.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Souffle' in tegame ai peperoni e formaggi",
                "course" => "Primo",
                "ingredients" => "formaggio cottage, peperone poblano, formaggio jack",
                "price" =>9.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Pesce alla messicana",
                "course" => "Secondo",
                "ingredients" => "filetto di Persico, pomodori, cipolla, peperone rosso, peperone verde , aglio, alloro",
                "price" =>16.30 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Chili con carne",
                "course" => "Secondo",
                "ingredients" => "carne di Manzo, peperoni verdi, cipolle, aglio, paprika dolce, peperoncino in polvere, pepronicno rosso piccante, cumino",
                "price" =>18.20 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Burrito con uova alla tex-mex Burritos con huevos",
                "course" => "Secondo",
                "ingredients" => "cipolla, pomodoro a pezzetti, peperoni, uova, origano, cumino, tortillas, fagioli rossi, cheddar, jalapeno",
                "price" =>22.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Mole de olla",
                "course" => "Secondo",
                "ingredients" => "carne di Manzo, prezzemolo, peperoncino rosso piccante, pomodoro pelato, cipolle, sesamo nero, pepe nero",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Zuppa di fagioli neri alla messicana",
                "course" => "Contorno",
                "ingredients" => "fagioli neri secchi, pancetta affumicata, brodo di pollo, peperoncino fresco, cipolle, alloro, cannella, pepe nero",
                "price" =>7.80 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Fagioli Pinto del Cile Crockpot Green",
                "course" => "Contorno",
                "ingredients" => "fagioli Pinto, peperoncino fresco, cipolle, alloro",
                "price" =>8.20 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Fajitas",
                "course" => "Piatto Unico",
                "ingredients" => "controfiletto di Manzo, petto di pollo, peperoni rossi, peperoni gialli, cipolle, lime, salsa Worcestershire, coriandolo ",
                "price" =>16.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Tacos",
                "course" => "Piatto Unico",
                "ingredients" => "Manzo, cipolle dorate, cumino, coriandolo, paprika affumicata, pepe nero",
                "price" =>16.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Tortillas",
                "course" => "Piatto Unico",
                "ingredients" => "Acuqa, farina, sale, olio",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Burrito",
                "course" => "Piatto Unico",
                "ingredients" => "Manzo, fagioli neri precotti, peperoni rossi, passata di pomodoro, cipolle bianche, cipolle rosse, aglio, peperoncino",
                "price" =>12.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Alegrías de amaranto",
                "course" => "Dolce",
                "ingredients" => "semi di zucca e miele ",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Alfajor",
                "course" => "Dolce",
                "ingredients" => "farina di mais, zucchero di canna e anice",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Buñuelos",
                "course" => "Dolce",
                "ingredients" => "zucchero e cannella",
                "price" =>6.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ]
        ],
 
        // Hawaiano
        "Hawaiano" =>[
            [
                "name"=> "Insalata hawaiana",
                "course" => "Antipasto",
                "ingredients" => "Gamberi, ananas, lattuga, rana pescatrice",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Antipasto Hawaiano",
                "course" => "Antipasto",
                "ingredients" => " ananas, petto di tacchino, arancia, gamberetti, uovo, lattuga, sale, salsa worchester, olio, limone",
                "price" =>6.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Spaghetti all'hawaiana",
                "course" => "Primo",
                "ingredients" => "cipolla, prezzemolo, peperoni, pinoli, curry, zafferano, peperoncino",
                "price" =>13.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Maiale Kalua ",
                "course" => "Secondo",
                "ingredients" => "ricoperto con foglie di banano e cucinato nell'imu",
                "price" =>22.60 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Maiale Lau Lau",
                "course" => "Secondo",
                "ingredients" => "ngredienti esotici, pollo, verdure",
                "price" =>18.20 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pollo Huli Huli ",
                "course" => "Secondo",
                "ingredients" => "soia, zucchero di canna, zenzero e frutta",
                "price" =>22.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Calamaro Luau",
                "course" => "Secondo",
                "ingredients" => "foglie di luau, sale, zucchero",
                "price" =>7.90 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Loco-moco",
                "course" => "Piatto Unico",
                "ingredients" => "uovo, carne di manzo, riso , salsa tamari, sale, pepe",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Lomi-lomi",
                "course" => "Piatto Unico",
                "ingredients" => "Salmone affumicato, cipolla, cipollotto, succo di limone, sale, pepe",
                "price" =>12.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "poke",
                "course" => "Piatto Unico",
                "ingredients" => "riso, salmone, avocado, alga wakame, mango, ravanello, cipollotto, salsa di soia, semi di sesamo",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Saimin",
                "course" => "Piatto Unico",
                "ingredients" => "kamaboko, pezzettini di maiale, alga nori, porro, noodles",
                "price" =>14.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Haupia",
                "course" => "Dolce",
                "ingredients" => "latte di cocco, zucchero, amido di mais",
                "price" =>6.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ]
        ],
 
        // Indiano
        "Indiano" =>[
            [
                "name"=> "Naan",
                "course" => "Antipasto",
                "ingredients" => "farina, acqua,yougurt bianco naturale, lievito di birra, sale",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Samosa ",
                "course" => "Antipasto",
                "ingredients" => "Farina, acqua, sale, patate, pisellini, cipolle, zenzero, anacardi, peperoncino, curcuma, cumino, sale",
                "price" =>6.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Papadum",
                "course" => "Antipasto",
                "ingredients" => " farina di fagioli o ceci, cumino",
                "price" =>5.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Raita",
                "course" => "Antipasto",
                "ingredients" => "yogurt, cetrioli, zucchine, cipollotti, aglio, sale, olio, pepe",
                "price" =>6.90 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pakora di verdure",
                "course" => "Antipasto",
                "ingredients" => "farina di ceci, verdure miste, curry, acqua, sale",
                "price" =>5.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Riso pilaf",
                "course" => "Primo",
                "ingredients" => "riso, cipolla, burro, zafferano, brodo di carne, sale",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pulao",
                "course" => "Primo",
                "ingredients" => "riso,cipolla, aglio, cannella, burro, cardamomo, pimento, zafferano, uva passa, mandorle",
                "price" =>11.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pollo al curry",
                "course" => "Secondo",
                "ingredients" => "pollo, burro, cipolla, farina, curry, panna , brodo, vino bianco",
                "price" =>16.30 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "pollo tandoori",
                "course" => "Secondo",
                "ingredients" => "cosce di pollo, yogurt intero, succo di limone, paprika dolce, paprika piccante, garam masala, sale",
                "price" =>14.20 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "paneer butter masala",
                "course" => "Secondo",
                "ingredients" => "paneer(formaggio indiano) , pomodori, zenzero, cipolle, aglio, anacardi, latte, garam masala, coriandolo, peperoncino, panna, ghee, sale, olio",
                "price" =>21.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "dahl di lenticchie",
                "course" => "Secondo",
                "ingredients" => "lenticchie rosse decorticate, carote, scalogno, brodo, curcuma, paprica, pepe nero, olio, zenzero, curry",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Phool gobi",
                "course" => "Contorno",
                "ingredients" => "cavolfiori, cumino, semi di fieno greco, zenzero, peperoncino in polvere, garam masala, curcuma macinata",
                "price" =>4.80 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Kamala Phoolkopi",
                "course" => "Contorno",
                "ingredients" => "cavolfiore, patate, curcuma macinata, alloro, pasta di zenzero, cipolle, peperoncino in polvere",
                "price" =>3.20 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Curry di cavolfiore",
                "course" => "Contorno",
                "ingredients" => "cavolfiore, patate, zenzero, chili in polvere, prezzemolo",
                "price" =>13.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Pollo tikka masala",
                "course" => "Piatto Unico",
                "ingredients" => "aglio, zenzero, garam masala, yogurt greco, pomodoro, cipolle, cumino, paprika affumicata, curcuma",
                "price" =>16.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Curry di gamberi",
                "course" => "Piatto Unico",
                "ingredients" => "Gamberi, pasta di curry, curcuma, peperoncino fresco, scalogno, aglio, prezzemolo",
                "price" =>23.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Curry vegetariano con zucca e ceci",
                "course" => "Piatto Unico",
                "ingredients" => "paprika piccante, zucca, ceci secchi, curry, curcuma in polvere, aglio, cipolle rosse, timo, brodo vegetale",
                "price" =>12.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Gulab jamun",
                "course" => "Dolce",
                "ingredients" => "ardamomo, acqua di rose, kewra e zafferano ",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Jalebi",
                "course" => "Dolce",
                "ingredients" => "farina di ceci e di mais",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Kaju katli",
                "course" => "Dolce",
                "ingredients" => "zafferano, cardamomo, ghee, latte, anacardi",
                "price" =>6.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ]
        ],
    ];

    protected $bevande = [
        //bevande
        [
            "name"=> "Acqua",
            "course" => "Bevande",
            "ingredients" => "1 litro , naturale o gassata",
            "price" =>1.5 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Vino bianco fermo",
            "course" => "Bevande",
            "ingredients" => "75 cl , vino fermo della casa. ",
            "price" =>6 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Vino bianco frizzante",
            "course" => "Bevande",
            "ingredients" => "75 cl , vino frizzante della casa. ",
            "price" =>6 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Vino rosso della casa",
            "course" => "Bevande",
            "ingredients" => "0.75 L , vino rosso della casa. ",
            "price" =>6.50 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Birra in bottiglia",
            "course" => "Bevande",
            "ingredients" => "66 cl. Heineken, Moretti,",
            "price" =>4 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Birra in lattina",
            "course" => "Bevande",
            "ingredients" => "33 cl , Heineken o Moretti",
            "price" =>3 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Coca cola in lattina",
            "course" => "Bevande",
            "ingredients" => "33cl",
            "price" =>2.50 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Fanta in lattina",
            "course" => "Bevande",
            "ingredients" => "33cl",
            "price" =>2.50 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Sprite in lattina",
            "course" => "Bevande",
            "ingredients" => "33cl",
            "price" =>2.50 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Coca cola in bottiglia",
            "course" => "Bevande",
            "ingredients" => "1.5 L",
            "price" =>3.50,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],

    ];

    public function run(Slug $slug)
    {


        $categories = Category::all();
        $categories->load('users');
        foreach ($categories as $category){
            foreach ($category->users as $user){
                foreach ($this->foodList[ucfirst($category->name)] as $food) { 
                    $new_food = new Food();
                    $new_food->fill($food);
                    $new_food->user_id= $user->id;
                    $new_food->slug= $slug($new_food->name,'foods');
                    $new_food->save();
                }
                foreach ($this->bevande as $bevande) { 
                    $new_food = new Food();
                    $new_food->fill($bevande);
                    $new_food->user_id= $user->id;
                    $new_food->slug= $slug($new_food->name,'foods');
                    $new_food->save();
                }
            }
        }
    }

}
