<?php

use Illuminate\Database\Seeder;

//model
use App\Food;
use App\User;
//zaninotto faker
use App\Services\Slug;

class CibiTableSeeder extends Seeder
{

    protected $foodList =
    [
        "italiano" =>[
            //antipasti
            [
                "name"=> "Antipasto all'italiana",
                "course" => "Antipasto",
                "ingredients" => "Tagliere di salumi tipici e una selezione di formaggi locali. Servito con focaccia ed erbe miste.",
                "price" =>9 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Caprese",
                "course" => "Antipasto",
                "ingredients" => "Pomodori,mozzarella,origano, olio EVO",
                "price" =>6 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Tris di bruschette",
                "course" => "Antipasto",
                "ingredients" => "Tre bruschette di pane rustico tostato con paté di olive, pomodori, salsiccia e provola affumicata.",
                "price" =>7 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Carpaccio di manzo",
                "course" => "Antipasto",
                "ingredients" => "Carpaccio di manzo, rucola, scaglie di parmigiano, olio di oliva",
                "price" =>5 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            
            //primi
            [
                "name"=> "Farfalle al pomodoro",
                "course" => "Primo",
                "ingredients" => "Pomodori pelati bio, basilico , aglio , olio extravergine d'oliva",
                "price" =>7.50 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Spaghetti alla carbonara",
                "course" => "Primo",
                "ingredients" => "Uova, guanciale, pecorino romano, pepe nero",
                "price" =>8.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Rigatoni all'amatriciana",
                "course" => "Primo",
                "ingredients" => "Pomodori pelati bio, guanciale, pecorino romano, peperoncino rosso, pepe nero",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 1,
            ],
            [
                "name"=> "Tortellini alla boscaiola",
                "course" => "Primo",
                "ingredients" => "Funghi, panna, prosciutto cotto, parmigiano, pepe nero",
                "price" =>7.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pasta alla norma",
                "course" => "Primo",
                "ingredients" => "Melanzana, pomodoro, ricotta di pecora, basilico",
                "price" =>8.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Risotto alla milanese",
                "course" => "Primo",
                "ingredients" => "Contiene burro,midollo di vitello e brodo di carne e zafferano.",
                "price" =>7.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            //secondi
            [
                "name"=> "Cotoletta di vitello",
                "course" => "Secondo",
                "ingredients" => "Fettine di vitello panate (con uova e pangrattato) e fritte",
                "price" =>8 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Scaloppine al limone",
                "course" => "Secondo",
                "ingredients" => "Fettine di vitello, burro, farina 00, succo di limone, pepe",
                "price" =>8 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Grigliata mista",
                "course" => "Secondo",
                "ingredients" => "Salsiccie e lonza di maiale, braciole d'agnello",
                "price" =>12 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pesce spada alla Pantesca",
                "course" => "Secondo",
                "ingredients" => "Filetto di spada, capperi, olive, cipolla e pomodoro ciliegino",
                "price" =>12 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Parmigiana di melanzane",
                "course" => "Secondo",
                "ingredients" => "Melanzane, passata di pomodoro, fiordilatte, parmigiano, basilico",
                "price" =>9.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Sformato di verdure",
                "course" => "Secondo",
                "ingredients" => "Melanzane, patate rosse, zucchine, scamorza affumiacata, peperoni, parmigiano",
                "price" =>11 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            //contorni
            [
                "name"=> "Olive all'ascolana",
                "course" => "Contorno",
                "ingredients" => "Olive,macinato misto di carne",
                "price" =>4.5 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Verdure grigliate",
                "course" => "Contorno",
                "ingredients" => "Melanzane e zucchine grigliate, olio EVO",
                "price" =>4 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Patate Fritte",
                "course" => "Contorno",
                "ingredients" => "Patate",
                "price" =>3 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Insalata mista",
                "course" => "Contorno",
                "ingredients" => "Insalata, rucola, cipolla, valeriana, spinacino",
                "price" =>3 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            //dolci
            [
                "name"=> "Tiramisù",
                "course" => "Dolce",
                "ingredients" => "Savoiardi, mascarpone, caffé, zucchero, uova",
                "price" =>3.5 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Panna cotta al cioccolato",
                "course" => "Dolce",
                "ingredients" => "Panna cotta con cioccolato al latte",
                "price" =>3 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Salame di cioccolato",
                "course" => "Dolce",
                "ingredients" => "Cioccolato fondente,biscotti secchi, rum",
                "price" =>3.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Cannoli siciliani",
                "course" => "Dolce",
                "ingredients" => "Ricotta di pecora, frutta candita, gocce di cioccolato",
                "price" =>4 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
        ],
        'cinese'=>[
             //antipasti
             [
                "name"=> "Edamame",
                "course" => "Antipasto",
                "ingredients" => "Fagioli di soia lessati",
                "price" =>3.20 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Eby Gyoza",
                "course" => "Antipasto",
                "ingredients" => "Ravioli di gamberi al vapore",
                "price" =>3.90 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Ebi Tai",
                "course" => "Antipasto",
                "ingredients" => "Gamberi avvolti da pasta fillo,fritti",
                "price" =>4.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Sake Cytro",
                "course" => "Antipasto",
                "ingredients" => "Salmone, cetriolo, maionese, salsa",
                "price" =>6.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Miso shiru",
                "course" => "Antipasto",
                "ingredients" => "Zuppa di miso con alghe e tofu",
                "price" =>3.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Involtini primavera",
                "course" => "Antipasto",
                "ingredients" => "Carote, cavolo cappuccio ,cipolle bianche, pepe bianco",
                "price" =>3.00 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            //primi
            [
                "name"=> "Riso cantonese",
                "course" => "Primo",
                "ingredients" => "Uova, prosciutto cotto, piselli, erba cipollina",
                "price" =>3.30 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Riso con gamberi",
                "course" => "Primo",
                "ingredients" => "Gamberi, piselli, uova",
                "price" =>3.80 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Spaghetti alla piastra con gamberi",
                "course" => "Primo",
                "ingredients" => "Gamberi, surimi, piselli, zucchine, uova",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Riso saltato con salmone e verdure",
                "course" => "Primo",
                "ingredients" => "Salmone, piselli, zucchine, carote, cipolla, uova",
                "price" =>4.00 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Gnocchi di riso con verdure",
                "course" => "Primo",
                "ingredients" => "Piselli, zucchine, carote, cipolla, erba cipollina",
                "price" =>3.80 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            //secondi
            [
                "name"=> "Pollo con bambù e funghi",
                "course" => "Secondo",
                "ingredients" => "Straccetti di pollo, funghi, bambù",
                "price" =>4.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Pollo alle mandorle",
                "course" => "Secondo",
                "ingredients" => "Straccetti di pollo, mandorle, carote, bambù",
                "price" =>4.30 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Maiale in salsa agrodolce",
                "course" => "Secondo",
                "ingredients" => "Maiale, cipollotti, salsa agrodolce",
                "price" =>4.30 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 0,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Tofu stufato",
                "course" => "Secondo",
                "ingredients" => "Tofu saltato con verdure",
                "price" =>4.30 ,
                "available" => 1,
                "is_vegan" => 1,
                "is_veggy" => 1,
                "is_lactose_free" => 1,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            //dolci
            [
                "name"=> "Gelato fritto",
                "course" => "Dolce",
                "ingredients" => "Gelato alla vaniglia fritto",
                "price" =>4.30 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Tiramisù",
                "course" => "Dolce",
                "ingredients" => "Savoiardi, mascarpone, caffé, zucchero, uova",
                "price" =>3.5 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 0,
                "is_hot" => 0,
            ],
            [
                "name"=> "Panna cotta al cioccolato",
                "course" => "Dolce",
                "ingredients" => "Panna cotta con cioccolato al latte",
                "price" =>3 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
            [
                "name"=> "Sake",
                "course" => "Bevande",
                "ingredients" => "Panna cotta con cioccolato al latte",
                "price" =>2.50 ,
                "available" => 1,
                "is_vegan" => 0,
                "is_veggy" => 1,
                "is_lactose_free" => 0,
                "is_gluten_free" => 1,
                "is_hot" => 0,
            ],
        ]
    ];

    protected $bevande = [
        //bevande
        [
            "name"=> "Acqua",
            "course" => "Bevande",
            "ingredients" => "1 litro , naturale o gassata",
            "price" =>1.5 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Vino bianco fermo",
            "course" => "Bevande",
            "ingredients" => "75 cl , vino fermo della casa. ",
            "price" =>6 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Vino bianco frizzante",
            "course" => "Bevande",
            "ingredients" => "75 cl , vino frizzante della casa. ",
            "price" =>6 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Vino rosso della casa",
            "course" => "Bevande",
            "ingredients" => "0.75 L , vino rosso della casa. ",
            "price" =>6.50 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Birra in bottiglia",
            "course" => "Bevande",
            "ingredients" => "66 cl. Heineken, Moretti,",
            "price" =>4 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Birra in lattina",
            "course" => "Bevande",
            "ingredients" => "33 cl , Heineken o Moretti",
            "price" =>3 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Coca cola in lattina",
            "course" => "Bevande",
            "ingredients" => "33cl",
            "price" =>2.50 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Fanta in lattina",
            "course" => "Bevande",
            "ingredients" => "33cl",
            "price" =>2.50 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Sprite in lattina",
            "course" => "Bevande",
            "ingredients" => "33cl",
            "price" =>2.50 ,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
        [
            "name"=> "Coca cola in bottiglia",
            "course" => "Bevande",
            "ingredients" => "1.5 L",
            "price" =>3.50,
            "available" => 1,
            "is_vegan" => 1,
            "is_veggy" => 1,
            "is_lactose_free" => 1,
            "is_gluten_free" => 1,
            "is_hot" => 0,
        ],
    ];

    public function run(Slug $slug)
    {
        $course =[
            'Antipasto',
            'Piatto Unico',
            'Primo',
            'Secondo',
            'Contorno',
            'Dolce',
            'Bevande'
        ];

        $faker = \Faker\Factory::create();
        $faker->addProvider(new \FakerRestaurant\Provider\it_IT\Restaurant($faker));
        $user = User::find(58);
        //creating up to 10 foods for each user
        foreach ($this->foodList['italiano'] as $food) { 
            $new_food = new Food();
            $new_food->fill($food);
            $new_food->user_id= $user->id;
            $new_food->slug= $slug($new_food->name,'foods');
            $new_food->save();
        }
        foreach ($this->bevande as $bevande) { 
            $new_food = new Food();
            $new_food->fill($bevande);
            $new_food->user_id= $user->id;
            $new_food->slug= $slug($new_food->name,'foods');
            $new_food->save();
        }
    }

}
